<#
.SYNOPSIS
    Back up Dropsofknowledge artifacts to a second private GitHub repository.
.DESCRIPTION
    Copies every small, valuable artifact (code, templates, fonts, docs,
    clip plans, transcripts, render state, QA reports/manifests, logs,
    Telegram ledger) into a dedicated backup clone and pushes it.

    Raw media is deliberately EXCLUDED:
      - source audio (*.amr/mp3/...) -> re-downloadable from the Telegram
        channel at any time via scripts\telegram_fetch.py
      - rendered mp4 / cache m4a / overlay+base png -> regenerated by
        RUN_PROJECT.cmd from inputs that are themselves backed up
    This keeps the backup repo tiny and fast; nothing unique is lost.

    Usage:
        powershell -File scripts\backup.ps1 [-RepoUrl URL] [-BackupDir DIR]
#>
param(
    [string]$RepoUrl = 'https://github.com/Dropsofknowledge/dok-backup.git',
    [string]$BackupDir = "$env:USERPROFILE\Documents\DropsofKnowledge_backup"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$Src = Split-Path -Parent (Split-Path -Parent $PSCommandPath)

function Log { param($m) Write-Host ("[backup] " + $m) }

# --- 0. sanity ---------------------------------------------------------------
if (-not (Test-Path -LiteralPath (Join-Path $Src '.git'))) {
    throw "Not running from the Dok repo: $Src"
}

# --- 1. prepare backup clone -------------------------------------------------
if (-not (Test-Path -LiteralPath (Join-Path $BackupDir '.git'))) {
    if (Test-Path -LiteralPath $BackupDir) {
        throw "Backup dir exists but is not a git repo: $BackupDir"
    }
    Log "Cloning $RepoUrl ..."
    & git clone $RepoUrl $BackupDir
    if ($LASTEXITCODE -ne 0) { throw 'git clone failed.' }
}
$BackupDir = (Resolve-Path -LiteralPath $BackupDir).Path

# --- 2. mirror selected artifacts --------------------------------------------
function Copy-One {
    param([string]$From,[string]$To)
    $destDir = Split-Path -Parent $To
    if (-not (Test-Path -LiteralPath $destDir)) {
        New-Item -ItemType Directory -Force -Path $destDir | Out-Null
    }
    Copy-Item -LiteralPath $From -Destination $To -Force
}

function Clear-And-Create {
    param([string]$Rel)
    $t = Join-Path $BackupDir $Rel
    if (Test-Path -LiteralPath $t) { Remove-Item -LiteralPath $t -Recurse -Force }
    New-Item -ItemType Directory -Force -Path $t | Out-Null
    return $t
}

# 2a. whole-tree folders (small by construction)
$treeTargets = @('scripts','harness','docs','fonts','assets','templates','state')
foreach ($t in $treeTargets) {
    $srcT = Join-Path $Src $t
    if (Test-Path -LiteralPath $srcT) {
        $dst = Clear-And-Create $t
        # never copy secrets or session files even if someone drops them there
        robocopy $srcT $dst /E /NFL /NDL /NJH /NJS /NP `
            /XF '.env' '*.session' '*.pyc' '*_token.json' | Out-Null
        if ($LASTEXITCODE -ge 8) { throw "robocopy failed for $t" }
    }
}

# 2b. root files
foreach ($f in @('README.md','START_HERE.cmd','LOGIN_TELEGRAM.cmd',
                 'BACKUP.cmd','.env.example')) {
    $p = Join-Path $Src $f
    if (Test-Path -LiteralPath $p) { Copy-One -From $p -To (Join-Path $BackupDir $f) }
}

# 2c. per-project artifacts
$projectsRoot = Join-Path $Src 'Projects'
if (Test-Path -LiteralPath $projectsRoot) {
    foreach ($proj in Get-ChildItem -LiteralPath $projectsRoot -Directory) {
        $rel = Join-Path 'Projects' $proj.Name

        # small top-level files
        foreach ($pat in @('clip_plan.json','transcript.*','render_state.json',
                           'layout.json','*.png')) {
            foreach ($f in Get-ChildItem -LiteralPath $proj.FullName `
                                              -Filter $pat -File) {
                Copy-One -From $f.FullName -To (Join-Path $BackupDir "$rel\$($f.Name)")
            }
        }

        # reports / logs mirrored wholesale (small json/log text)
        foreach ($sub in @('reports','logs')) {
            $s = Join-Path $proj.FullName $sub
            if (Test-Path -LiteralPath $s) {
                $d = Clear-And-Create (Join-Path $rel $sub)
                Copy-Item -Path (Join-Path $s '*') -Destination $d -Recurse -Force
            }
        }

        # per-clip outputs: only manifest/report/captions/preview (no media)
        $outSrc = Join-Path $proj.FullName 'output'
        if (Test-Path -LiteralPath $outSrc) {
            Clear-And-Create (Join-Path $rel 'output') | Out-Null
            foreach ($clip in Get-ChildItem -LiteralPath $outSrc -Directory) {
                $cdst = Join-Path $BackupDir "$rel\output\$($clip.Name)"
                New-Item -ItemType Directory -Force -Path $cdst | Out-Null
                foreach ($pat in @('manifest.json','report.json',
                                   'captions.ass','preview.jpg')) {
                    foreach ($f in Get-ChildItem -LiteralPath $clip.FullName `
                                       -Filter $pat -File) {
                        Copy-One -From $f.FullName -To (Join-Path $cdst $f.Name)
                    }
                }
            }
        }
    }
}

# --- 3. commit + push --------------------------------------------------------
Push-Location $BackupDir
try {
    & git add -A
    $porcelain = (& git status --porcelain)
    if ($porcelain) {
        $stamp = Get-Date -Format 'yyyy-MM-dd HH:mm'
        & git commit -m "Backup $stamp"
        if ($LASTEXITCODE -ne 0) { throw 'git commit failed.' }
        $branch = (& git rev-parse --abbrev-ref HEAD)
        & git push -u origin $branch
        if ($LASTEXITCODE -ne 0) { throw 'git push failed.' }
        Log "Pushed backup to $RepoUrl"
    } else {
        Log 'Nothing changed since last backup.'
    }
} finally {
    Pop-Location
}
Log 'Done.'
